name: hypothesis

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"
  pull_request:
    types: [labeled]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
 build_ubuntu:
    name: 'Ubuntu'
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || github.event.label.name == 'test-with-hypothesis' }}
    env:
      OPENSSL_VER: 1.1.1q
      PYTHONSTRICTEXTENSIONBUILD: 1
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ubuntu-hypothesis-${{ hashFiles('Tools/hypothesis/requirements.txt') }}
        restore-keys: |
          ubuntu-hypothesis-
    - name: 'Install Dependencies'
      run: sudo ./.github/workflows/posix-deps-apt.sh && sudo apt-get install wamerican
    - name: 'Configure CPython'
      run: ./configure --with-pydebug
    - name: 'Build CPython'
      run: make -j4

    - name: 'Install dependencies'
      run: make -C Tools/hypothesis PYTHON=../../python venv
    - name: Run hypothesis tests
      run: make -C Tools/hypothesis PYTHON=../../python test
